"""Render analysis/error_annotations.csv as a readable Markdown file for review.

    python analysis/make_error_review.py path/to/dialogsum.test.jsonl

The test file comes from the original DialogSum release
(github.com/cylnlp/dialogsum, DialogSum_Data/dialogsum.test.jsonl).
"""

import csv
import json
import sys

LABELS = {
    "speaker": "Speaker confusion",
    "factual": "Unsupported detail or wrong causal link",
    "missed_point": "Misses the point",
    "ok": "Faithful, covers the main point",
}

src = {json.loads(l)["fname"]: json.loads(l) for l in open(sys.argv[1])}
pred = {}
for line in open("results/v2.jsonl"):
    r = json.loads(line)
    pred.setdefault(r["id"].rsplit("_", 1)[0], r["raw_output"])
rows = list(csv.DictReader(open("analysis/error_annotations.csv")))
order = ["speaker", "factual", "missed_point", "ok"]
rows.sort(key=lambda r: (order.index(r["label"]), int(r["sample_index"])))

out = ["# v2 error analysis: 50 test dialogues", "",
       "Generated by `analysis/make_error_review.py` from `error_annotations.csv`. "
       "To change a judgement, edit the CSV and re-run.", ""]
for label in order:
    group = [r for r in rows if r["label"] == label]
    out += [f"## {LABELS[label]} ({len(group)})", ""]
    for r in group:
        d = src[r["dialogue_id"]]
        out += [f"### [{r['sample_index']}] {r['dialogue_id']}", ""]
        if r["note"]:
            out += [f"**Judgement:** {r['note']}", ""]
        out += ["**Model output**", "", "```", pred[r["dialogue_id"]].strip(), "```", "",
                "**Reference summaries**", ""]
        out += [f"{i}. {d[f'summary{i}']}" for i in (1, 2, 3)]
        out += ["", "<details><summary>Dialogue</summary>", "", "```", d["dialogue"], "```",
                "", "</details>", ""]
open("analysis/error_review.md", "w").write("\n".join(out))
print("wrote analysis/error_review.md")
